<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Ecpay\Ecpaypayment\Block\Order\Failure
 */
?>
<?php if ($block->getRealOrderId()) :?>
    <p><?php echo $block->escapeHtml(__('Order #') . $block->getRealOrderId()) ?></p>
<?php endif ?>
<?php if ($error = $block->getErrorMessage()) :?>
    <p><?php echo $block->escapeHtml($error) ?></p>
<?php endif ?>
<p>
    <?php echo $block->escapeHtml(
        __('Click <a href="%1">here</a> to continue shopping.', $block->escapeUrl($block->getContinueShoppingUrl())),
        ['a']
    ) ?>
</p>
